version: "3"
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    volumes:
      - ./localstack/data:/tmp/localstack/data
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_DEFAULT_REGION=dummy
      - AWS_SECRET_ACCESS_KEY=dymmy
      - DATA_DIR=/tmp/localstack/data
      - SERVICES=s3 # this can be a comma separated list of services you want to start
      - TZ=Europe/London
    ports:
      - '4566:4566' # these ports will be different for different services.
